api:
  build: .
  links:
    - db
  volumes:
   - "${PWD}:/srv/proxypool"
  ports:
    - "8000:8000"
  environment:
    PGHOST: db
    PGDATABASE: postgres
    PGUSER: postgres
  command: python IPProxy.py

db:
  image: "postgres:9.5.6"
  environment:
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: postgres
